# Generated by Django 3.2 on 2021-04-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transactionID', models.CharField(max_length=256)),
                ('discountID', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('paymentMethod', models.CharField(choices=[('DEB', 'Debit Card'), ('CRD', 'Credit Card'), ('NET', 'Net Banking'), ('UPI', 'UPI')], max_length=3)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
    ]
