# Generated by Django 3.2 on 2021-04-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='NULL', max_length=4, null=True),
        ),
    ]
