# Generated by Django 3.2 on 2021-04-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.CharField(max_length=5)),
                ('seatType', models.CharField(choices=[('PREMIUM', 'Premium'), ('NORMAL', 'Normal'), ('RECLINER', 'Recliner'), ('FRONT', 'Front')], max_length=20)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.theater')),
            ],
        ),
    ]
