version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # command: psql -U postgres -d postgres -c 'SELECT setval('tablename_id_seq', (SELECT MAX(id) FROM tablename)+1)'
  web:
    build: .
    command: >
        bash -c "
        python manage.py makemigrations
        && python manage.py migrate
        && python manage.py < reset_pk.py
        && python manage.py loaddata db.json
        && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
